# -*- coding: utf-8 -*-
"""23-PC-cgussen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c-tszxaOvT96lDAY_4pDLWilq0vK2ll-

# Q1: Make a simple page with an embedded viz and host it.
"""

import plotly.express as px

gapminder_df = px.data.gapminder()

fig = px.choropleth(gapminder_df, locations='iso_alpha', 
                    color='lifeExp',
                    hover_name='country', 
                    animation_frame='year', range_color=[10, 100])
fig.show()

import plotly.io as pio

# creating an empty html file
fh = open('data_viz_full_embed.html', 'w')
fh.close()

pio.write_html(fig, file='data_viz_full_embed.html', auto_open=True, full_html=True) # create one html page with the viz embed

fh = open('data_viz_div_embed.html', 'w')
fh.close()

pio.write_html(fig, file='data_viz_div_embed.html', auto_open=True, full_html=False) # create one DIV only with the viz embed